config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/infonew', to: 'person#new'
  post   '/infonew', to: 'person#create'
  get    '/infoconew', to: 'company#new'
  post   '/infoconew', to: 'company#create'
  get    '/search', to: 'users#search', as: 'search'
  post   '/find', to: 'users#find', as: 'find'
  resources :users
  resources :person
  resources :company
  resources :relation
end

app/models/person.rb
class Person < ApplicationRecord
  validates :description,  length: { maximum: 150 }

  ratyrate_rateable "punctuality", "performance", "personal_image"

  has_many :relations
end

app/controllers/person_controller.rb
class PersonController < ApplicationController
  def new
    @kind = Person.new
  end

  def show
    @person = current_person_by_user
  end

  def create
    @person = Person.new(info_params)
    if @person.save
      redirect_to current_user
    else
      render 'new'
    end
  end

  def edit
    @person = current_person_by_user
  end

  def update
    @person = current_person_by_user
    if @person.update(info_params)
      flash[:success] = "Profile updated"
      redirect_to @person
    else
      render 'edit'
    end
  end

  def index
    #aqui se pondra los repute
  end

private
  def current_person_by_user
    current_user.person
  end

  def info_params #parámetros fuertes para evitar la vulnerabilidad de asignación de masas 
      params.require(:person).permit(:name, :lastname, :born, :ocupation, 
                                   :soc_stat, :page, :description, :user_id)
  end
end

app/helpers/person_helper.rb
module PersonHelper
end

app/views/person/edit.html.erb
<% provide(:title, 'Edit Personal Information') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@person) do |f| %>
      <%= render 'shared/error_messages_person' %>

      <%= f.label "Firstname" %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :lastname %>
      <%= f.text_field :lastname, class: 'form-control' %>
      
      <%= f.label "Birthday" %>
      <%= f.text_field :born, class: 'form-control' %>

      <%= f.label :ocupation %>
      <%= f.text_field :ocupation, class: 'form-control' %>
      
      <%= f.label "Social stat" %>
      <%= f.text_field :soc_stat, class: 'form-control' %>
      
      <%= f.label :page %>
      <%= f.text_field :page, class: 'form-control' %>
      
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.hidden_field :user_id, value: current_user.id %>
      
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
   
</div>

app/views/person/index.html.erb
index.html.erb

app/views/person/new.html.erb
<% provide(:title, 'Personal Information') %>
<h1>Personal Information</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@kind, url: infonew_path) do |f| %> <!-- Es necesario generar una ruta que lleve a la creacion de la informacion -->
      <!-- Verificar que el render de error menssages nos combiene -->

      <%= f.label "Firstname" %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :lastname %>
      <%= f.text_field :lastname, class: 'form-control' %>
      
      <%= f.label "Birthday" %>
      <%= f.text_field :born, class: 'form-control' %>

      <%= f.label :ocupation %>
      <%= f.text_field :ocupation, class: 'form-control' %>
      
      <%= f.label "Social stat" %>
      <%= f.text_field :soc_stat, class: 'form-control' %>
      
      <%= f.label :page %>
      <%= f.text_field :page, class: 'form-control' %>
      
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
      
      <%= f.hidden_field :user_id, value: current_user.id %>
      
      <%= f.submit "Save my Information", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/person/show.html.erb
<% provide(:title, 'Personal Information') %>
<h1>Personal Information</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="gravatar_person">
      <%= gravatar_for current_user %>
    </div>
    <section class="user_info">
      <h2>
        <em><b>Firstname:</b></em>
        <%= @person.name%><br><br>

        <em><b>Lastname:</b></em>
        <%= @person.lastname%><br><br>

        <em><b>Birthday:</b></em>
        <%= @person.born%><br><br>

        <em><b>Ocupation:</b></em>
        <%= @person.ocupation%><br><br>

        <em><b>Social Stat:</b></em>
        <%= @person.soc_stat%><br><br>

        <em><b>Personal page:</b></em>
        <%= @person.page%><br><br>

        <em><b>Description:</b></em>
        <%= @person.description%><br><br>

        <em><b>Member since:</b></em>
        <%= @person.created_at%><br><br>
      </h2>
    </section>
  </aside>
  <%= link_to "Edit", edit_person_path(@person), class: "btn btn-primary btn-block" %>
  
</div>