config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/infonew', to: 'person#new'
  post   '/infonew', to: 'person#create'
  get    '/infoconew', to: 'company#new'
  post   '/infoconew', to: 'company#create'
  get    '/search', to: 'users#search', as: 'search'
  post   '/find', to: 'users#find', as: 'find'
  resources :users
  resources :person
  resources :company
  resources :relation
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { email.downcase! }
  # validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  #***********************************
  validates :profile, presence: true
  has_one :person
  has_one :company
  ratyrate_rater
  #***********************************

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index 
    #Tengo que hacer algo al respecto de este, puede que no lo necesite
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    user_type = user_params[:profile]
    p user_type
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Peacock!" 
      if user_type == "0"
        redirect_to infonew_path #@user
      else
        redirect_to infoconew_path #@user
      end
    else
      render 'new'
    end
  end

  def edit
    # @user = User.find(params[:id])
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def search
    @user = User.new
    @person = Person.new
    @company = Company.new
  end

  def find
    
  end

  private

    def user_params #parámetros fuertes para evitar la vulnerabilidad de asignación de masas 
      params.require(:user).permit(:email, :password,
                                   :password_confirmation, :profile)
    end

    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    if user.person
      image_tag(gravatar_url, alt: user.person.name, class: "gravatar")
    else
      image_tag(gravatar_url, alt: user.company.name_co, class: "gravatar")
    end
  end
end

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <% if user.company%>
  <%= link_to user.company.name_co, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %><br>
  <%= user.company.type_co%>
  <% elsif user.person%>
  <%= link_to user.person.name + " " + user.person.lastname, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %><br>
  <%= user.person.ocupation%>
  <%end%>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your account</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/find.html.erb
find.html.erb

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

<%= link_to "Search", search_path, class: "btn btn-primary btn-block" %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :profile, class: "checkbox inline" do %>
        <%= f.check_box :profile %>
        <span>Company</span><br>
      <% end %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/search.html.erb
<% provide(:title, "Search") %>
<h1>Update your account</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: find_path) do |f| %>

      <%= f.label "Email" %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.submit "Search by email", class: "btn btn-primary" %>
    <% end %>
    <%= form_for(@company, url: find_path) do |f| %>

      <%= f.label "Company name" %>
      <%= f.text_field :name_co, class: 'form-control' %>

      <%= f.label "Departament" %>
      <%= f.text_field :type_co, class: 'form-control' %>

      <%= f.label "Company name" %>
      <%= f.text_field :name_co, class: 'form-control' %>
      <%= f.submit "Search for company", class: "btn btn-primary" %>
    <% end %>

    <%= form_for(@person, url: find_path) do |f| %>

      <%= f.label "Name" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label "Ocupation" %>
      <%= f.text_field :ocupation, class: 'form-control' %>

      <%= f.submit "Search for person", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<% if @user.person%>
<% provide(:title, @user.person.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.person.name %><br><br>
      </h1>
      <h4>
        <%= link_to "Information", person_path %><br><br>
        <%= link_to "Reputation", person_path %>
      </h4> 
    </section>
  </aside>
</div>
<% else%>
<% provide(:title, @user.company.name_co) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.company.name_co %><br><br>
      </h1>
      <h4>
        <%= link_to "Information", company_path %><br><br>
        <%= link_to "Employees", company_index_path %><br><br>
        <%= link_to "Reputation", company_path %><br><br>
        <%= link_to "New project announcements", company_path %><br><br>
        <%= link_to "Post a proyect need", company_path %>
      </h4>
    </section>
  </aside>
</div>
<% end %>