config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/infonew', to: 'person#new'
  post   '/infonew', to: 'person#create'
  get    '/infoconew', to: 'company#new'
  post   '/infoconew', to: 'company#create'
  get    '/search', to: 'users#search', as: 'search'
  post   '/find', to: 'users#find', as: 'find'
  resources :users
  resources :person
  resources :company
  resources :relation
end

app/models/company.rb
class Company < ApplicationRecord
  validates :description,  length: { maximum: 150 }

  ratyrate_rateable "punctuality", "service", "quality"

  has_many :relations
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  def new
    @kind = Company.new
  end

  def show
    @company = current_company_by_user
  end

  def create
    @company = Company.new(infoco_params)
    if @company.save
      redirect_to current_user
    else
      render 'new'
    end
  end

  def edit
    @company = current_company_by_user
  end

  def update
    @company = current_company_by_user
    if @company.update(infoco_params)
      flash[:success] = "Profile updated"
      redirect_to @company
    else
      render 'edit'
    end
  end

  def index
    @kind = Company.new
    #aqui se pondra los repute
  end

private
  def current_company_by_user
    current_user.company
  end

  def infoco_params #parámetros fuertes para evitar la vulnerabilidad de asignación de masas 
      params.require(:company).permit(:name_co, :ceo_co, :page, 
                                      :type_co, :latitud, :longitud, :description, :user_id)
  end
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/views/company/edit.html.erb
<% provide(:title, 'Edit Information') %>
<h1>Update company profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@company) do |f| %>
      <%= render 'shared/error_messages_company' %>

      <%= f.label "Company name" %>
      <%= f.text_field :name_co, class: 'form-control' %>
      
      <%= f.label :ceo_co %>
      <%= f.text_field :ceo_co, class: 'form-control' %>
      
      <%= f.label :page %>
      <%= f.text_field :page, class: 'form-control' %>

      <%= f.label "Type of company" %>
      <%= f.text_field :type_co, class: 'form-control' %>
      

      <%= f.hidden_field :latitud, class: 'form-control', value: @company.latitud %>
      <%= f.hidden_field :longitud, class: 'form-control', value: @company.longitud %>
      
      <%= render 'maps/geoloc_map' %><br>
    
      <%= f.button "Localizar", type:"button", onclick:"localizar()", class: "btn btn-primary" %><br><br>
      
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
      
      <%= f.hidden_field :user_id, value: current_user.id %>
      
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
   
</div>

app/views/company/index.html.erb
<% provide(:title, 'Employees') %>
<h1>Staff</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="gravatar_company">
      <%= gravatar_for current_user %>
    </div><br><br><br>
    <section class="user_staff">
     <%current_user.company.relations.each do |employee|%>
     <% e_id = employee.person_id%>
     <% p_id = Person.find(e_id).user_id %>
     <% @user = User.find(p_id)%>
     <section class="user_info">
      <h4>
        <%= gravatar_for @user, size: 40 %>
        <%= @user.person.name %>
        <%= @user.person.lastname %>
        <% if current_user.company && relation = Relation.find_by(sudo: current_user.id) %>
          | <%= link_to "Fire", relation, method: :delete,data: { confirm: "You sure?" } %>
        <% end %><br>
      </h4>
      <h5>
        <%= @user.person.ocupation %><br>
        <%= link_to "Peack", relation_path(e_id) %>
      </h5>
    </section>
    <%end%>
    </section><br><br><br>
  </aside>
  <%= link_to "Add Employee", new_relation_path, class: "btn btn-primary btn-block" %>
  
</div>

app/views/company/new.html.erb
<% provide(:title, 'Information') %>
<h1>Company Information</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@kind, url: infoconew_path) do |f| %> <!-- Es necesario generar una ruta que lleve a la creacion de la informacion -->
      <!-- Verificar que el render de error menssages nos combiene -->

      <%= f.label "Business name" %>
      <%= f.text_field :name_co, class: 'form-control' %>
      
      <%= f.label :ceo_co %>
      <%= f.text_field :ceo_co, class: 'form-control' %>
      
      <%= f.label :page %>
      <%= f.text_field :page, class: 'form-control' %>

      <%= f.label "Type of company" %>
      <%= f.text_field :type_co, class: 'form-control' %>
      
      <%= f.hidden_field :latitud, class: 'form-control' %>
      <%= f.hidden_field :longitud, class: 'form-control' %>
      
      <%= render 'maps/geoloc_map' %>
      
      <%= f.button "Localizar", type:"button", onclick:"localizar()", class: "btn btn-primary" %><br><br>
      
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
      
      <%= f.hidden_field :user_id, value: current_user.id %>

      <%= f.submit "Save Information", class: "btn btn-primary" %>

    <% end %>
   </div>

app/views/company/show.html.erb
<% provide(:title, 'Information') %>
<h1>Company Information</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="gravatar_company">
      <%= gravatar_for current_user %>
    </div>
    <section class="user_info">
      <h2>
        <em><b>Company:</b></em>
        <%= @company.name_co%><br><br>

        <em><b>CEO:</b></em>
        <%= @company.ceo_co%><br><br>

        <em><b>Company page:</b></em>
        <%= @company.page%><br><br>

        <em><b>Type of company:</b></em>
        <%= @company.type_co%><br><br>

        <em><b>Description:</b></em>
        <%= @company.description%><br><br>

        <em><b>Member since:</b></em>
        <%= @company.created_at%><br><br>

        <%= form_for(@company) do |f| %>
        <%= f.hidden_field :latitud, value: @company.latitud %>
        <%= f.hidden_field :longitud, value: @company.longitud %>
        <%= render 'maps/show_map' %>
      <%end%>
      </h2>
    </section>
  </aside>
  <%= link_to "Edit", edit_company_path(@company), class: "btn btn-primary btn-block" %>
  
</div>